apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: sscs-mcp-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sscs-mcp-server 
  name: sscs-mcp-server
spec:
  port:
    targetPort: 8000 
  tls:
    insecureEdgeTerminationPolicy: Allow
  to:
    kind: Service
    name: sscs-mcp-server
    weight: 100 
